{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapedit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapedit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapedit/mapedit_{{ version }}.tar.gz
  sha256: edb27a8531d0db0375fed6b4401a812d8afaa5a6db0da6a8feed69d2552f41b2

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dt
    - r-assertthat
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leafem
    - r-leaflet >=2.0.1
    - r-leaflet.extras >=1.0
    - r-leafpm
    - r-leafpop
    - r-mapview
    - r-miniui
    - r-raster
    - r-rstudioapi
    - r-scales
    - r-sf >=0.5_2
    - r-shiny
    - r-shinywidgets >=0.4.3
    - r-tmaptools
  run:
    - r-base
    - r-dt
    - r-assertthat
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leafem
    - r-leaflet >=2.0.1
    - r-leaflet.extras >=1.0
    - r-leafpm
    - r-leafpop
    - r-mapview
    - r-miniui
    - r-raster
    - r-rstudioapi
    - r-scales
    - r-sf >=0.5_2
    - r-shiny
    - r-shinywidgets >=0.4.3
    - r-tmaptools

test:
  commands:
    - $R -e "library('mapedit')"           # [not win]
    - "\"%R%\" -e \"library('mapedit')\""  # [win]

about:
  home: https://github.com/r-spatial/mapedit
  license: MIT
  summary: Suite of interactive functions and helpers for selecting and editing geospatial data.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: mapedit
# Title: Interactive Editing of Spatial Data in R
# Description: Suite of interactive functions and helpers for selecting and editing geospatial data.
# Version: 0.7.0
# Authors@R: c( person("Tim", "Appelhans", role = c("aut", "cre"), email = "tim.appelhans@gmail.com"), person("Kenton", "Russell", role = c("aut")), person("Lorenzo", "Busetto", role = c("aut")), person("Josh", "O'Brien", role = c("ctb")), person("Jakob", "Gutschlhofer", role = c("ctb")), person("Matt", "Johnson", role = c("ctb")), person("Eli", "Pousson", role = "ctb", comment = c(ORCID = "0000-0001-8280-1706")) )
# URL: https://github.com/r-spatial/mapedit
# BugReports: https://github.com/r-spatial/mapedit/issues
# License: MIT + file LICENSE
# Depends: R (>= 3.1.0)
# Imports: assertthat, dplyr, DT, htmltools (>= 0.3), htmlwidgets, jsonlite, leafem, leaflet (>= 2.0.1), leaflet.extras (>= 1.0), leafpm, leafpop, mapview, methods, miniUI, raster, rstudioapi, scales, sf (>= 0.5-2), shiny, tmaptools, shinyWidgets (>= 0.4.3)
# Suggests: crayon, sp
# Enhances: geojsonio
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: no
# Packaged: 2025-04-20 07:25:58 UTC; tim
# Author: Tim Appelhans [aut, cre], Kenton Russell [aut], Lorenzo Busetto [aut], Josh O'Brien [ctb], Jakob Gutschlhofer [ctb], Matt Johnson [ctb], Eli Pousson [ctb] (<https://orcid.org/0000-0001-8280-1706>)
# Maintainer: Tim Appelhans <tim.appelhans@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-04-20 08:20:01 UTC
