{% set version = "0.5.0" %}

package:
  name: r-mapedit
  version: {{ version }}

source:
  fn: mapedit_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mapedit_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapedit/mapedit_{{ version }}.tar.gz
  sha256: eb296e8412d57b453eaddd3607c0ad3a50db1cd32621ad44e2479b3ead9e2d9b

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leaflet
    - r-leaflet.extras
    - r-mapview
    - r-miniui
    - r-sf >=0.5_2
    - r-shiny
  run:
    - r-base
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leaflet
    - r-leaflet.extras
    - r-mapview
    - r-miniui
    - r-sf >=0.5_2
    - r-shiny

test:
  commands:
    - $R -e "library('mapedit')"  # [not win]
    - "\"%R%\" -e \"library('mapedit')\""  # [win]

about:
  home: https://cran.r-project.org/package=mapedit
  license: MIT
  license_file: LICENSE
  summary: Suite of interactive functions and helpers for selecting and editing geospatial data.

extra:
  recipe-maintainers:
    - ocefpaf
