{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mapedit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapedit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapedit/mapedit_{{ version }}.tar.gz
  sha256: 3b4a20a953bd1aeb4c9e63971e6e69894889e55e1cc40441f6ab356db898e0a2

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dt
    - r-assertthat
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leafem
    - r-leaflet >=2.0.1
    - r-leaflet.extras >=1.0
    - r-leafpm
    - r-leafpop
    - r-mapview
    - r-miniui
    - r-raster
    - r-rstudioapi
    - r-scales
    - r-sf >=0.5_2
    - r-shiny
    - r-shinywidgets >=0.4.3
    - r-tmaptools
  run:
    - r-base
    - r-dt
    - r-assertthat
    - r-dplyr
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-jsonlite
    - r-leafem
    - r-leaflet >=2.0.1
    - r-leaflet.extras >=1.0
    - r-leafpm
    - r-leafpop
    - r-mapview
    - r-miniui
    - r-raster
    - r-rstudioapi
    - r-scales
    - r-sf >=0.5_2
    - r-shiny
    - r-shinywidgets >=0.4.3
    - r-tmaptools

test:
  commands:
    - $R -e "library('mapedit')"           # [not win]
    - "\"%R%\" -e \"library('mapedit')\""  # [win]

about:
  home: https://github.com/r-spatial/mapedit
  license: MIT
  summary: Suite of interactive functions and helpers for selecting and editing geospatial data.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: mapedit
# Title: Interactive Editing of Spatial Data in R
# Description: Suite of interactive functions and helpers for selecting and editing geospatial data.
# Version: 0.5.0
# Date: 2019-03-16
# Authors@R: c( person("Tim", "Appelhans", role = c("aut", "cre"), email = "tim.appelhans@gmail.com"), person("Kenton", "Russell", role = c("aut")), person("Lorenzo", "Busetto", role = c("aut")) )
# URL: https://github.com/r-spatial/mapedit
# BugReports: https://github.com/r-spatial/mapedit/issues
# License: MIT + file LICENSE
# Depends: R (>= 3.1.0)
# Imports: dplyr, htmltools (>= 0.3), htmlwidgets, jsonlite, leaflet (>= 2.0.1), leaflet.extras (>= 1.0), leafpm, mapview, miniUI, sf (>= 0.5-2), shiny
# Suggests: crayon
# Enhances: geojsonio
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-16 21:13:16 UTC; kentr
# Author: Tim Appelhans [aut, cre], Kenton Russell [aut], Lorenzo Busetto [aut]
# Maintainer: Tim Appelhans <tim.appelhans@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-16 22:50:08 UTC
