appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jxQf7zeb/n0cdOdgxqcbPBRyHxXpTzeqybCMBbOgvMjwmiZqmoS+C62U9sr+q5WMSX2HEj5YfTpSQ7OUzeDMNsWIGkNX7QnV1k86T2lnsOF9BlJljnP1ti21GwOHV7NPmXQUQsEtw6FR3z26HcHYoHkwZunCiksLkETwpxK4ossHeEd6gghA8jj9IP05OTTJUV+yA2ieWtUGDeG4XDkSlQ2jWVcSNLiUVaxw3ioVjETlQ+NSVMEeAmOPdhdmwc9eUgC96zY45e2quQNrN8Z7fAEa0s2EamlvUwAO23HxzZw/V2jSyOYaIqs26ys6gfPTkzy4+vRr+MOJrRTx/W72bxjfPwJmL+i5pvqK/U3bpnCMTZdVs6rtosawi5BclbDks5d6/fLxYZ5B+qiOYkd3DYw+pgQ4ikbjxeX+miM6Jk8Z9ajiefnCELM5ZFelh3enGf8ewFSnXZbEb6kqJ6zE9pGTaR2DQSOcA2uPsWMC8IcrUf9z0cuYYbV4D0owPqFOCMpHJ9SypPUlJBXYpJdGFT2L2mNbmQAZk/rlng7sx8AVPuPV0A7GcWwxLRCkh9EjdMOgT2EbNiHwhG9LrvrAe0BwPacWLXjmTqmh34nXxjJNikP2D+7W+9J1zShq2xjuA95+Mq78CGx43yesRkPtGiSRNbjFFlAu3dGS3jzO7/s=}
bot:
  automerge: true
